''' Write a python script to
Construct two numpy 3D arrays A1 and A2 of any shape set by the user at run time and the elements are randomly generated by the system. Perform the following steps
1) Construct an array by selecting all the elements of the first array (A1) that are divisible by 5
2) Construct another array by selecting all the elements of the second array (A2) that are divisible by 4
3) Join 1 and 2 to form a single dimensional array and construct the largest possible square matrix from it
'''
import numpy as np

shape_A1 = tuple(map(int, input("Enter the shape of A1 (e.g., 3 3 3): ").split()))
shape_A2 = tuple(map(int, input("Enter the shape of A2 (e.g., 3 3 3): ").split()))

A1 = np.random.randint(1, 101, size=shape_A1)
A2 = np.random.randint(1, 101, size=shape_A2)

print("\nArray A1:")
print(A1)
print("\nArray A2:")
print(A2)

A1_div5 = A1[A1 % 5 == 0]

A2_div4 = A2[A2 % 4 == 0]

joined_array = np.concatenate((A1_div5, A2_div4))

n = int(np.floor(np.sqrt(len(joined_array))))

square_matrix = joined_array[:n*n].reshape(n, n)

print("\nThe largest possible square matrix is:")
print(square_matrix)
